name: .NET Build & Test

on:
  push:
    branches: [ "main" ]   # 当推送到 main 分支时运行
  pull_request:
    branches: [ "main" ]   # 当有人提 PR 时运行

jobs:
  build:
    runs-on: ubuntu-latest   # 运行环境（Linux）

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # 拉取代码

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # 你用的 .NET 版本，可以改成 6.0/7.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
